---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  APP_PATH_PREFIX: {{ .Values.ingress.path | quote }}
  APP_CORS_ALLOW_ORIGIN: {{ .Values.app.cors_allow_origin | quote }}
  APP_TRUSTED_PROXIES: {{ .Values.app.trusted_proxies | quote }}
  APP_REDIS_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_CACHE_SERVER: {{ .Values.app.redis.server | quote }}
  APP_REDIS_CACHE_PORT: {{ .Values.app.redis.port | quote }}
  APP_REDIS_CACHE_DB: {{ .Values.app.redis.cache_db | quote }}
  APP_REDIS_CACHE_PREFIX: {{ .Values.app.redis.prefix | quote }}
  APP_ELASTIC_URL: {{ .Values.app.elastic_url | quote }}
  APP_ENABLE_NO_HITS: {{ .Values.app.enbled_no_hits | quote }}
  PHP_PM_TYPE: {{ .Values.app.php.type | quote }}
  PHP_PM_MAX_CHILDREN: {{ .Values.app.php.max_children | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-nginx-config
data:
  APP_PATH_PREFIX: {{ .Values.ingress.path | quote }}
  PHP_FPM_SERVER: "127.0.0.1"
  PHP_FPM_SERVER_PORT: "9000"
