api_platform:
    # Documentation
    title: 'DDB Cover Service'
    description: >-
        This service provides covers for library materials indexed by isbn, issn, faust, pid.
        The service is provided by [Danskernes Digitale Bibliotek](https://www.danskernesdigitalebibliotek.dk/)

        ### Authentication notes

        Authentication is done via OAuth2 against auth.dbc.dk. To obtain a valid token follow instructions in
        [1.2. Password Grant](https://github.com/DBCDK/hejmdal/blob/master/docs/oauth2.md#12-password-grant).
        To use the "Authorize" option in this tool use your 'client_id' and 'client_secret' and fill in '@' for
        both username and password.

        ### Implementation notes

        Currently the API is not fully implemented. The following features are missing:

        * Generic Covers: parameter is currently ignored. Service doesn't yet provide generic covers.

        * Pagination: not implemented.

        * Oauth: not implemented.
    version: '2.0'
    show_webby: false
    swagger:
        versions: [3]
    enable_re_doc: false

    formats:
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    mapping:
        paths:
            - '%kernel.project_dir%/src/Api/Dto'
    patch_formats:
        json: ['application/merge-patch+json']

    collection:
        pagination:
            enabled: false

    doctrine:
        enabled: false

    elasticsearch:
        # Note: trailing slash added (Fos\Elastica requires elastic host without trailing slash)
        # @TODO change when Fos\Elastica is removed from stack
        hosts: ['%env(ELASTIC_URL)%']

    graphql:
        enabled: false
        graphiql:
            enabled: false

    exception_to_status:
        App\Api\Exception\RequiredParameterMissingException: 'HTTP_BAD_REQUEST'
        App\Api\Exception\UnknownIdentifierTypeException: 'HTTP_BAD_REQUEST'
