Feature:
  As a developer I want to be able to test that my behat test setup works. Including
  being able to reset and pupulate both database and elasticsearch schema.

  Scenario: View documentation
    And I send a "GET" request to "/api"
    Then the response status code should be 200
    And the header "Content-Type" should be equal to "text/html; charset=UTF-8"

  @createSchema
  Scenario: View single cover
    Given the following search entries exits:
      | identifier | type | url                      | autogenerated | image_format |
      | 1234       | ISBN | http://test.com/1234.jpg | true          | jpeg         |
    And I add "Accept" header equal to "application/ld+json"
    And I send a "GET" request to "/api/cover/isbn/1234"
    Then the response status code should be 200
    And the header "Content-Type" should be equal to "application/ld+json; charset=utf-8"
