---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-landing
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-landing
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-landing
        networking/allow-ingress-access: "true"
        networking/allow-monitoring-access: "true"
        networking/allow-internet-access: "{{ .Release.Name }}"
    spec:
      containers:
        - name: frontend
          image: danskernesdigitalebibliotek/cover-service-landing:{{ .Values.app.image.version }}
          imagePullPolicy: {{ .Values.app.image.imagePullPolicy }}
          resources:
            requests:
              memory: '32Mi'
              cpu: '50m'
            limits:
              memory: '64Mi'
              cpu: '100m'
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 80
              name: pod-http-port
