---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-landing
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
