<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mi="https://cover.dandigbib.org/ns/moreinfo" xmlns:miw="https://cover.dandigbib.org/ns/moreinfo_wsdl" targetNamespace="https://cover.dandigbib.org/ns/moreinfo_wsdl">
	<wsdl:documentation>
		This file is part of moreinfo (https://opensource.dbc.dk/services/moreinfo)
		Copyright (c) 2010, Dansk Bibliotekscenter a/s,  Tempovej 7-11, DK-2750 Ballerup, Denmark. CVR: 15149043
	</wsdl:documentation>
	<wsdl:types>
		<xs:schema elementFormDefault="qualified">
			<xs:import namespace="https://cover.dandigbib.org/ns/moreinfo" schemaLocation="moreinfo.xsd"/>
		</xs:schema>
	</wsdl:types>

	<wsdl:message name="moreInfoRequest">
		<wsdl:part name="body" element="mi:moreInfoRequest"/>
	</wsdl:message>

	<wsdl:message name="moreInfoResponse">
		<wsdl:part name="body" element="mi:moreInfoResponse"/>
	</wsdl:message>

	<wsdl:portType name="moreInfoPortType">
		<wsdl:operation name="moreInfo">
			<wsdl:input message="miw:moreInfoRequest"/>
			<wsdl:output message="miw:moreInfoResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="moreInfoBinding" type="miw:moreInfoPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="moreInfo">
			<soap:operation soapAction="http://cover.dandigbib.org"/>
			<wsdl:input name="moreInfoRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="moreInfoResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="moreInfoService">
		<wsdl:port name="moreInfoPortType" binding="miw:moreInfoBinding">
      <soap:address location="https://cover.dandigbib.org/2.11/"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
